# Generated by Django 6.0.7 on 2026-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudFile', '0002_sharedfile_owner_downloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
